import NewProject from "@/components/NewProject";
import React from "react";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Naqeeb | Add New Project",
  description: "Generated by create next app",
};

const CreateProject = () => {
  return (
    <div className="">
      <NewProject />
    </div>
  );
};

export default CreateProject;
