import NewProject from "@/components/NewProject";
import EditProjectComp from "@/components/editProject";
import { prisma } from "@/lib/prisma";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Naqeeb | Edit Project",
  description: "Generated by create next app",
};

interface EditPageProps {
  params: {
    id: string;
  };
}

const EditProject = async ({ params: { id } }: EditPageProps) => {
  const project = await prisma.project.findUnique({
    where: { id },
  });

  return (
    <div>
      <div className="">
        <EditProjectComp project={project} />
      </div>
    </div>
  );
};

export default EditProject;
