import UserMsg from "@/components/UserMsg";
import { prisma } from "@/lib/prisma";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Naqeeb | User Messages",
  description: "Generated by create next app",
};

const UserMessages = async () => {
  const userMessages = await prisma.message.findMany({});
  return (
    <div className="w-screen ">
      <UserMsg userMessages={userMessages} />
    </div>
  );
};

export default UserMessages;
