import { getServerSession } from "next-auth";

import { authOptions } from "@/lib/authOption";
import { prisma } from "@/lib/prisma";
import DataGridComp from "@/components/dataGridComp";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Naqeeb | Projects",
  description: "Generated by create next app",
};

const AllProjects = async () => {
  const session = await getServerSession(authOptions);
  const projects = await prisma.project.findMany();

  return (
    <div className=" ">
      <DataGridComp projects={projects} />
    </div>
  );
};

export default AllProjects;
