import Contact from "@/components/Contact";
import HeroSection from "@/components/HeroSection";
import PageWrapper from "@/components/PageWrapper";
import Projects from "@/components/Projects";
import Skills from "@/components/Skills";
import Services from "@/components/services";
import { prisma } from "@/lib/prisma";
import Image from "next/image";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home | Naqeeb",
  description: "Generated by create next app",
};

export default async function Home() {
  const projects = await prisma.project.findMany({ orderBy: { id: "desc" } });
  return (
    <div className="w-full overflow-hidden">
      <section className="sticky top-0 ">
        <HeroSection />
      </section>
    </div>
  );
}
